source 'https://rubygems.org'

# Specify your gem's dependencies in elastic-extensions.gemspec
gemspec

if File.exist? File.expand_path("../../elastic-api/elastic-api.gemspec", __FILE__)
  gem 'elastic-api', :path => File.expand_path("../../elastic-api", __FILE__), :require => false
end

if File.exist? File.expand_path("../../elastic-transport/elastic-transport.gemspec", __FILE__)
  gem 'elastic-transport', :path => File.expand_path("../../elastic-transport", __FILE__), :require => false
end

if File.exist? File.expand_path("../../elastic/elastic.gemspec", __FILE__)
  gem 'elastic', :path => File.expand_path("../../elastic/", __FILE__)
end
